title: Hector de la Rosa Prado
subtitle: Resume page
description: >- # this means to ignore newlines until "baseurl:"
  Get to know me a bit more, and checkout my projects while you're here!

url: "https://hoftherose.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:

    - text: About Me
      url: /
    - text: Portfolio
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Hector de la Rosa Prado
author_bio: University student currently enrolled in the UNAM Mexico. Interested in machine and deep learning research and applications.
author_email: "hoftherose@gmail.com"
author_location: Mexico
author_website_url: "http://hoftherose.github.io"

author_work_experiences:
            - company_name: National Autonomous University of Mexico ENES Morelia
              company_logo: unam.png
              company_url: http://www.enesmorelia.unam.mx/
              designation: Teachers Assitant
              description: Evaluated assignments and gave lectures on various subjects like Formal Automata Theory, Linear Algebra and Deep Learning 
              visibility: true
            - company_name: Mexican Math Olympiad for Basic Education, Morelia (OMMEB)
              company_logo: ommeb.png
              company_url: https://microsoft.com
              designation: State Delegate
              description: Planning courses and gathering funding for the state competition.
              visibility: true

author_education_details:
              - college_logo: unam.png
                college_name: UNAM ENES Morelia
                college_url: https://www.enesmorelia.unam.mx/
                college_degree: IT in Science
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: hoftherose
github_username:  hoftherose
facebook_username: hoftherose
linkedin_username: hoftherose
#behance_username: hoftherose
instagram_username: hoftherose
#medium_username: hoftherose
telegram_username: hoftherose
#dribbble_username: hoftherose
#flickr_username: hoftherose

#for comments using disqus
disqus_shortname: 

# wakatime username (coding activity)
wakatime_username: hoftherose

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# formspree (contact form)
formspree_email: 

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-158631044-2

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: OXKDLZ60QW
  index_name: site # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: a1102632d8a723715dbf610f0b871aed

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Gallery
defaults:
  -
    scope:
      path: "portfolio"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
